name: booking_system
description: A comprehensive booking and decoration management system.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  # ... (بقية المكتبات)

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- إدارة قواعد البيانات: Sembast ---
  sembast: ^3.7.0
  path_provider: ^2.1.3 # لتحديد مسار قاعدة البيانات على الجوال
  path: ^1.9.0         # لمعالجة المسارات بشكل موثوق
  sembast_web: ^2.3.0    # لدعم الويب (اختياري لكن موصى به)

  # --- إدارة الحالة والتنقل ---
  flutter_riverpod: ^2.5.1
  get_it: ^7.7.0
  go_router: ^14.2.0
  
  # --- مكتبات مساعدة ---
  intl: ^0.20.2
  cupertino_icons: ^1.0.2

  printing: ^5.14.0
  pdf: ^3.11.0

  image_picker: ^1.1.2 # أو أحدث إصدار

  table_calendar: ^3.1.2 # أو أحدث إصدار

  file_picker: ^8.0.6 # أو أحدث إصدار

  flutter_local_notifications: ^17.2.1 # أو أحدث إصدار

  file_saver: ^0.2.12 # لحفظ الملف على الجهاز


  url_launcher: ^6.3.1 # أو أحدث إصدار
  crypto: ^3.0.6




dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # --- أدوات التحليل والجودة ---
  flutter_lints: ^4.0.0
  # لا حاجة لـ build_runner الآن لأن Sembast لا تتطلب توليد كود

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
